---
- name: "Create directory"
  file: 
    path: ~/backendapp
    state: directory

- name: "Extract zipped artifact"  
  unarchive:
    src: artifact.tar.gz
    dest: ~/backendapp

- name: Start npm service
  shell: |
    pm2 start npm -- start
  args:
    chdir: ~/backendapp/

