---
- name: "Unarchive zipped artifact"
  unarchive:
    src: artifact.tar.gz

- name: "Installing dependencies"
  shell: |
    npm install
    npm run build
    npm install pm2 --location=global
    pm2 stop default
    pm2 start npm -- start